### ISSUE TITLE
update css JEU TEMPOREL

### ISSUE THREAD

**Issue by RFillion** [tim-montmorency/2022#4]
J'ai update le css, voir si ça marche.

**Comment by gllmAR** [comment]
fix via 8bd4e00eae475bcc15cde29723c0d24fc65b3596

screenshot du site en ligne 

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/7544151/151413013-322c749e-88a3-4db3-8831-8122bc61c434.png">
